main: ${PACKAGE}.${NAME}
name: NBG-Plugin
version: "0.0.1"
api-version: "1.21"
author: Code-ga
description: New bie gang server plugin
softdepend: ['Multiverse-Core', 'Multiverse-Inventories']
commands:
  spawn:
    description: Base command for EXAMPLE
    usage: "Help you back to spawn by /spawn"
    aliases: spawn
  giveGachaChest:
    description: Give the gacha chest to you
    usage: "giveGachaChest"
    aliases: gachachest, gachachests
    permission: giveGachaChest
  shop:
    description: Shop
    usage: "shop"
    aliases: shop